import { defineConfig } from "tsdown";

// oxlint-disable-next-line import/no-anonymous-default-export
export default defineConfig({
  minify: true,
  entry: [
    "./src/index.ts",
    "./src/index.next.ts",
    "./src/index-slider.ts",
    "./src/index-third.ts",
    "./src/index-video.ts",
    "./src/index-style.ts",
    "./src/index-dom.ts",
    // use client:
    "src/components/Analytics/Analytics/AnalyticsContext.ts",
    "src/components/Analytics/Analytics/AnalyticsProvider.tsx",
    "src/components/Analytics/Analytics/AnalyticsViewport.tsx",
    "src/components/Animate/Animate/Animate.tsx",
    "src/components/Form/Form/Form.tsx",
    "src/components/Form/Form/FormProvider.tsx",
    "src/components/Form/Input/Input.tsx",
    "src/components/Form/Label/Label.tsx",
    "src/components/Form/Label/LabelProvider.tsx",
    "src/components/Form/Textarea/Textarea.tsx",
    "src/components/Generic/BackButton/BackButton.tsx",
    "src/components/Generic/BackTopButton/BackTopButton.tsx",
    "src/components/Generic/Ready/Ready.tsx",
    "src/components/Generic/Resource/Resource.tsx",
    "src/components/Generic/Resource/ResourceProvider.tsx",
    "src/components/Generic/Share/Share.tsx",
    "src/components/Header/Header/Header.tsx",
    "src/components/Header/HeaderNav/HeaderNav.tsx",
    "src/components/Pagination/Pagination/Pagination.tsx",
    "src/components/Pagination/Pagination/PaginationPage.tsx",
    "src/components/Surface/Accordion/Accordion.tsx",
    "src/components/Surface/Counter/Counter.tsx",
    "src/components/Surface/FlipCard/FlipCard.tsx",
    "src/components/Surface/Media/Media.tsx",
    "src/components/Surface/Media/MediaImage.tsx",
    "src/components/Surface/Media/MediaVideoYoutube.tsx",
    "src/components/Surface/Mosaic/Mosaic.tsx",
    "src/components/Surface/ScrollProgress/ScrollProgress.tsx",
    "src/components/Surface/Slider/Slider.tsx",
    "src/components/Surface/VLibras/VLibras.tsx",
    "src/services/hooks/useAnalytics.ts",
    "src/services/hooks/useInViewport.ts",
    "src/services/hooks/useLocalStorage.tsx",
    "src/services/hooks/useReady.ts",
    "src/services/PortalService.tsx",
  ],
  platform: "browser",
  deps: { neverBundle: true },
  tsconfig: "./tsconfig.build.json",
});
